### ISSUE TITLE
bug: reset spinner after failed send; improve error alert (difficult to tell there was an error)

### ISSUE THREAD

**Issue by barbaraliau** [nomad-xyz/nomad-app#106]
also not sure if these are just extra logs or we are calling more things than needed before getting an error.

![Screen Shot 2022-01-11 at 21 06 08](https://user-images.githubusercontent.com/10275927/149062274-ad309d42-8bf6-49f1-8075-b7c97cf8c898.png)
![Screen Shot 2022-01-11 at 21 08 42](https://user-images.githubusercontent.com/10275927/149062328-47f66696-9a6d-4a87-97fb-c5437494186e.png)
![Screen Shot 2022-01-11 at 21 08 53](https://user-images.githubusercontent.com/10275927/149062332-96421e88-198b-45ef-9624-ca6a75cc2bd9.png)

**Comment by ErinHales** [comment]
Closed in #254
