### ISSUE TITLE
bug: countdown timer gets stuck; need to refresh / open in new tab to reset

### ISSUE THREAD

**Issue by pranaymohan** [nomad-xyz/nomad-app#166]
Feedback from Moonbeam team:

Hey Nomad team, just some friendly user-feedback to share. Possibly user error or a hiccup in my internet connection, but when I was bridging from Ethereum network to Moonbeam network, the countdown timer seemed to get stuck. Refreshing the page or opening a new window with the same link gave the correct time remaining. Is it possible to more frequently update the UI with the timer?

**Comment by ErinHales** [comment]
I believe this issue was fixed a while ago.  Haven't had any other complaints
