### ISSUE TITLE
sentry: catch the error in the event a user rejects a transaction 

### ISSUE THREAD

**Issue by yourbuddyconner** [nomad-xyz/nomad-app#210]
Sentry issue: [BRIDGE-GUI-B](https://sentry.io/share/issue/45f4c1dacbec4e76abd03e8a23544976/)

Excerpt of Error:
```
{
code: 4001, 
message: User rejected the request., 
stack: 
{
  "code": 4001,
  "message": "User rejected the request.",
...
```

Looks like the promise is rejected and whatever is throwing the error is returning it in a format that is unexpected by the error handling pipeline.

**Comment by Imti** [comment]
Closed by Erin as part of https://github.com/nomad-xyz/nomad-app/pull/293
