### ISSUE TITLE
sentry: catch Network Not Found error when the user hasn't selected a network yet

### ISSUE THREAD

**Issue by yourbuddyconner** [nomad-xyz/nomad-app#212]
Sentry: [BRIDGE-GUI-90](https://sentry.io/share/issue/f79646ca2b014202837bb9f5269a437a/)

If the user hasn't selected a network yet, we should catch this error and only let it bubble up if the user has already interacted with the network-picker.

**Comment by ErinHales** [comment]
Fixed
