### ISSUE TITLE
Use config data from the new @nomad-xyz/configuration npm package

### ISSUE THREAD

**Issue by Imti** [nomad-xyz/nomad-app#255]
The new sdk uses the NomadConfig to instantiate, so the GUI has to be updated with the new config/sdk before we deploy a new chain

Update gui to pull from `@nomad-xyz/configuration` and use that config data structure for network configs

**Comment by ErinHales** [comment]
Luke pointed out that we don't need to update everything to use the new configuration.  Probably smart to initially just update the SDK and use `let context = new BridgeContext("production");` which will pull from configuration internally.

**Comment by ErinHales** [comment]
Then we can update the rest of the GUI to pull from configuration values later

**Comment by Imti** [comment]
Good point, should just need to tackle [this issue](https://github.com/nomad-xyz/nomad-app/issues/256) then

**Comment by Imti** [comment]
Closed by (https://github.com/nomad-xyz/nomad-app/pull/272)
