### ISSUE TITLE
Update to use new sdk packages

### ISSUE THREAD

**Issue by Imti** [nomad-xyz/nomad-app#256]
Will need to use our new [`@nomad-xyz/sdk-bridge`](https://www.npmjs.com/package/@nomad-xyz/sdk-bridge) and [`@nomad-xyz/sdk`](https://www.npmjs.com/package/@nomad-xyz/sdk) packages

Work involved should just be updating to use the above new packages and updating imports

**Comment by ErinHales** [comment]
Update: 
1. Changes to `syncWebAssembly`
2. removed other `sdk-bridge` imports. 
3. Imported `/store/modules/sdk` into `main.ts` so it would import `sdk-bridge` and instantiate `BridgeContext` on load.

We have a semi-working version yay!

**Comment by ErinHales** [comment]
#263 closed this issue
