### ISSUE TITLE
bug: "Cannot read properties of undefined (reading 'blockExplorer')" on tx page

### ISSUE THREAD

**Issue by Imti** [nomad-xyz/nomad-app#270]
On the transaction page, there's an error thrown `Cannot read properties of undefined (reading 'blockExplorer')` which originates from 'Transaction/Details.vue` in this code block:

```
explorerLink(): string {
  const n = networks[this.originNet]
  return `${n.blockExplorer}/tx/${this.$route.params.id}`
},
```

`this.originNet` is undefined and is not defined until the component is mounted. So the error is thrown, but it doesn't present in the UI in any way.

**Comment by ErinHales** [comment]
Closed in #276
