### ISSUE TITLE
bug: no error shown for invalid transaction page route params

### ISSUE THREAD

**Issue by ErinHales** [nomad-xyz/nomad-app#288]
Should show error if:
- Not a valid network
- Malformed tx hash
- tx for (network, txHash) not found in indexer

https://media.discordapp.net/attachments/966042583157571624/966341201206870076/8.jpg

**Comment by anna-carroll** [comment]
just gotta make sure that indexer latency doesn't cause the error state when transitioning to the status page from the transfer page -- because the transaction won't be indexed yet

**Comment by ErinHales** [comment]
> just gotta make sure that indexer latency doesn't cause the error state when transitioning to the status page from the transfer page -- because the transaction won't be indexed yet

Oh yeah, that won't be affected at all 👍
