### ISSUE TITLE
bug: minutes remaining flickers

### ISSUE THREAD

**Issue by ErinHales** [nomad-xyz/nomad-app#291]
When the confirmAt check fails, we fall back on calculating from relayedAt and add a 10 minute buffer.  This is causing minutes remaining to flicker +- 10 minutes

**Comment by Imti** [comment]
@ErinHales Is this a UI issue? Like if we faded the old number out / new number in, would that help?

**Comment by ErinHales** [comment]
Yeah, so it was because we were setting confirmAt twice.  Should be fixed in the linked PR
