### ISSUE TITLE
Notification shows up on 404 page

### ISSUE THREAD

**Issue by pranaymohan** [nomad-xyz/nomad-app#324]
Expected Behavior -- should not show notification on 404 page

Alternatively, can design something fun for 404 page :)

<img width="1352" alt="Screen Shot 2022-04-30 at 6 45 20 PM" src="https://user-images.githubusercontent.com/5403615/166126347-d569f0ef-6a53-4d0b-9437-b4b33689e6e2.png">

**Comment by ErinHales** [comment]
This notification is already gone. But noted for the next time we put one up
