### ISSUE TITLE
Show user balance of tokens 

### ISSUE THREAD

**Issue by pranaymohan** [nomad-xyz/nomad-app#326]
Would be helpful for users to see how much of each token they have in their wallet when they are selecting / deciding which one to bridge over. See example request included in screenshot.
<img width="347" alt="Screen Shot 2022-05-02 at 10 49 03 AM" src="https://user-images.githubusercontent.com/5403615/166264795-ba7b3827-d094-4076-8b47-0ee2c174cd5f.png">

**Comment by ErinHales** [comment]
This was in original designs. However, there was a concern about it being query intensive. However, I think we'll only show a handful of default assets + a few user-added whitelist tokens, so probably would be fine

**Comment by ErinHales** [comment]
Implemented
