### ISSUE TITLE
Switch from development.nomad.xyz -> dev.nomad.xyz

### ISSUE THREAD

**Issue by Imti** [nomad-xyz/nomad-app#38]
Great suggestion from Anna

1. create dev branch off of development branch
2. set dev branch as default branch
3. setup dev environment on netlify
4. delete development branch

**Comment by ErinHales** [comment]
Not gonna lie, this seems super low priority. Plus, I like the idea of naming being consistent with our configs/agents where it's development/staging.  Should we just close this?

**Comment by Imti** [comment]
> Not gonna lie, this seems super low priority. Plus, I like the idea of naming being consistent with our configs/agents where it's development/staging. Should we just close this?

Yeah I'm fine with that
