### ISSUE TITLE
UI Suggestion: Origin -> Destination arrow swaps origin and destination

### ISSUE THREAD

**Issue by rswanson** [nomad-xyz/nomad-app#401]
### Describe the feature you would like

Hi there! 

Minor suggestion for improving the bridge UX- in a lot of swap or bridge UI's the arrow that links the origin and the destination will be interact-able and clicking it would swap the origin and destination (see screenshot below). Could be a nice easy way for users to swap directions on their bridge transactions.

![photo_2022-07-09_09-27-51](https://user-images.githubusercontent.com/1462505/178626722-aacfc95b-89a5-4377-9008-48a8d1f38a61.jpg)

**Comment by ErinHales** [comment]
Outdated
